/*
 * TIMER_Private.h
 *
 *  Created on: Aug 28, 2023
 *      Author: Mostafa Hisham
 *      Layer : MCAL
 *      SWC   : TIMER-PRIVATE
 */

#ifndef MCAL_TIMER_PRIVATE_H_
#define MCAL_TIMER_PRIVATE_H_

#define TCCR0_WGM00			6						// WAVERFORM GENERATION MODE bit0
#define TCCR0_COM01			5						//COMPARE MATCH OUTPUT MODE	BIT2
#define TCCR0_COM00			4						//COMPARE MATCH OUTPUT MODE BIT1
#define TCCR0_WGM01			3						// WAVERFORM GENERATION MODE bit1
#define TCCR0_CS02			2						//PRESCALER bit2
#define TCCR0_CS01			1						//PRESCALER bit1
#define TCCR0_CS00			0


#define TCCR1A_COM1A1		7						//COMPARE MATCH OUTPUT CH1A MODE BIT2
#define TCCR1A_COM1A0		6						//COMPARE MATCH OUTPUT CH1A MODE BIT1
#define TCCR1A_COM1B1		5						//COMPARE MATCH OUTPUT CH1B MODE BIT2
#define TCCR1A_COM1B0		4						//COMPARE MATCH OUTPUT CH1B MODE BIT1
#define TCCR1A_WGM11		1						// WAVERFORM GENERATION MODE BIT1
#define TCCR1A_WGM10		0						// WAVERFORM GENERATION MODE BIT0




#define TCCR1B_ICNC1 		7
#define TCCR1B_ICES1		6
#define TCCR1B_WGM12		3
#define TCCR1B_WGM13		4
#define TCCR1B_CS12			2
#define TCCR1B_CS11			1
#define TCCR1B_CS10			0



#define TCCR2_WGM20 		6
#define TCCR2_COM21			5
#define TCCR2_COM20			4
#define TCCR2_WGM21			3
#define TCCR2_CS22			2
#define TCCR2_CS21			1
#define TCCR2_CS20			0

#define TIMSK_OCIE2			7
#define TIMSK_TOIE2			6
#define TIMSK_OCIE1A		4
#define TIMSK_OCIE1B		3
#define TIMSK_TOIE1			2
#define TIMSK_OCIE0			1
#define TIMSK_TOIE0			0

#endif /* MCAL_TIMER_PRIVATE_H_ */
